# Generated by Django 4.0.6 on 2022-10-06 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CafeMain",
            fields=[
                ("cafe_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "main_name",
                    models.CharField(max_length=165, verbose_name="CafeName(Main)"),
                ),
                (
                    "is_operated",
                    models.BooleanField(default=1, verbose_name="isOperated"),
                ),
                (
                    "is_franchise",
                    models.BooleanField(default=False, verbose_name="isFranchised"),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="phone")),
                ("hours", models.JSONField(default=dict, verbose_name="OpenTime")),
                ("sns", models.JSONField(default=dict, verbose_name="SNS")),
                (
                    "registrant",
                    models.CharField(max_length=20, verbose_name="registrant"),
                ),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DATE"),
                ),
                (
                    "modify_dt",
                    models.DateTimeField(auto_now=True, verbose_name="MODIFY DATE"),
                ),
            ],
            options={
                "verbose_name": "Cafe Main",
                "db_table": "cafe_main",
                "ordering": ("-modify_dt",),
            },
        ),
        migrations.CreateModel(
            name="CafeAddress",
            fields=[
                (
                    "cafe_id",
                    models.ForeignKey(
                        db_column="cafe_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="cafe_address",
                        serialize=False,
                        to="cafespot.cafemain",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("sido", models.CharField(max_length=40, verbose_name="시도")),
                ("sigungu", models.CharField(max_length=40, verbose_name="시군구")),
                ("doro", models.CharField(max_length=40, verbose_name="도로명")),
                ("doro_code", models.CharField(max_length=10, verbose_name="도로명코드")),
                (
                    "sangse",
                    models.CharField(
                        blank=True, default=None, max_length=165, verbose_name="상세주소"
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DATE"),
                ),
                (
                    "modify_dt",
                    models.DateTimeField(auto_now=True, verbose_name="MODIFY DATE"),
                ),
            ],
            options={
                "db_table": "cafe_address",
                "ordering": ("-cafe_id",),
            },
        ),
        migrations.CreateModel(
            name="CafeFranchise",
            fields=[
                (
                    "cafe_id",
                    models.ForeignKey(
                        db_column="cafe_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="cafe_franchise",
                        serialize=False,
                        to="cafespot.cafemain",
                    ),
                ),
                ("branch_name", models.CharField(max_length=100, verbose_name="Menu")),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DATE"),
                ),
                (
                    "modify_dt",
                    models.DateTimeField(auto_now=True, verbose_name="MODIFY DATE"),
                ),
            ],
            options={
                "verbose_name": "Menu Franchise",
                "verbose_name_plural": "Menu Franchises",
                "db_table": "cafe_franchise",
                "ordering": ("-modify_dt",),
            },
        ),
        migrations.CreateModel(
            name="CafeSubName",
            fields=[
                (
                    "cafe_sub_name_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "sub_name",
                    models.CharField(max_length=100, verbose_name="CafeName(Sub)"),
                ),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DATE"),
                ),
                (
                    "modify_dt",
                    models.DateTimeField(auto_now=True, verbose_name="MODIFY DATE"),
                ),
                (
                    "cafe_id",
                    models.ForeignKey(
                        db_column="cafe_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cafe_sub_name",
                        to="cafespot.cafemain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cafe Name",
                "verbose_name_plural": "Cafe Names",
                "db_table": "cafe_sub_name",
                "ordering": ("-modify_dt",),
            },
        ),
        migrations.CreateModel(
            name="CafeMenuImage",
            fields=[
                (
                    "menu_image_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("image_url", models.CharField(max_length=2000, verbose_name="Menu")),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DATE"),
                ),
                (
                    "modify_dt",
                    models.DateTimeField(auto_now=True, verbose_name="MODIFY DATE"),
                ),
                (
                    "cafe_id",
                    models.ForeignKey(
                        db_column="cafe_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cafe_menu_image",
                        to="cafespot.cafemain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Name Image",
                "verbose_name_plural": "Menu Name Images",
                "db_table": "cafe_menu_image",
                "ordering": ("-modify_dt",),
            },
        ),
        migrations.CreateModel(
            name="CafeMenu",
            fields=[
                ("menu_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40, verbose_name="Menu")),
                ("price", models.PositiveIntegerField(verbose_name="PRICE")),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DATE"),
                ),
                (
                    "modify_dt",
                    models.DateTimeField(auto_now=True, verbose_name="MODIFY DATE"),
                ),
                (
                    "cafe_id",
                    models.ForeignKey(
                        db_column="cafe_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cafe_menu",
                        to="cafespot.cafemain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Name",
                "verbose_name_plural": "Menu Names",
                "db_table": "cafe_menu",
                "ordering": ("-modify_dt",),
            },
        ),
    ]
