# Generated by Django 4.0.6 on 2022-10-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cafespot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafefranchise",
            name="cafe_id",
            field=models.OneToOneField(
                db_column="cafe_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                related_name="cafe_franchise",
                serialize=False,
                to="cafespot.cafemain",
            ),
        ),
    ]
